blueprintName: message-board

services:
  - type: web
    name: message-board
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: JDBC_DATABASE_URL
        value: jdbc:mysql://trolley.proxy.rlwy.net:18820/railway?useSSL=false&serverTimezone=Asia/Tokyo
      - key: JDBC_DATABASE_USERNAME
        value: root
      - key: JDBC_DATABASE_PASSWORD
        value: HDAEGCuFmyyJUDvvcQzZCsUFNVFwzcUc